#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# TaskHub — Development Environment Setup
# ============================================================
# Usage:
#   chmod +x scripts/deploy-dev.sh
#   ./scripts/deploy-dev.sh
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env.local"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { echo -e "${CYAN}[INFO]${NC}  $1"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

echo ""
echo "============================================"
echo "  TaskHub — Dev Environment Setup"
echo "============================================"
echo ""

cd "$PROJECT_DIR"

# --------------------------------------------------
# 1. Check Node.js version
# --------------------------------------------------
info "Checking Node.js version..."

if ! command -v node &> /dev/null; then
    error "Node.js not found. Install Node.js 20+ from https://nodejs.org"
    exit 1
fi

NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    error "Node.js 20+ required, found v$(node -v). Please upgrade."
    exit 1
fi
ok "Node.js $(node -v)"

# --------------------------------------------------
# 2. Install dependencies (root + meeting-server)
# --------------------------------------------------
info "Installing root dependencies..."

if [ -f "package-lock.json" ]; then
    npm ci --silent
else
    npm install --silent
fi
ok "Root dependencies installed"

if [ -d "$PROJECT_DIR/meeting-server" ]; then
    info "Installing meeting-server dependencies..."
    pushd "$PROJECT_DIR/meeting-server" > /dev/null
    if [ -f "package-lock.json" ]; then
        npm ci --silent
    else
        npm install --silent
    fi
    popd > /dev/null
    ok "meeting-server dependencies installed"
fi

# --------------------------------------------------
# 3. Create data directories (db + recordings)
# --------------------------------------------------
info "Creating data directories..."
mkdir -p "$PROJECT_DIR/data"
mkdir -p "$PROJECT_DIR/data/recordings"
ok "data/ and data/recordings/ ready"

# --------------------------------------------------
# 4. Generate .env.local if missing
# --------------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
    info "Creating .env.local from template..."

    # Generate secrets
    JWT_SECRET="dev-$(node -e "console.log(require('crypto').randomBytes(16).toString('hex'))")"
    ENCRYPTION_KEY=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
    LIVEKIT_API_KEY="APIdev$(node -e "console.log(require('crypto').randomBytes(6).toString('hex'))")"
    LIVEKIT_API_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")

    cat > "$ENV_FILE" <<EOF
# ===== Generated by deploy-dev.sh =====

# JWT
JWT_SECRET=${JWT_SECRET}

# Admin (seeded on first start)
ADMIN_EMAIL=admin@taskhub.local
ADMIN_PASSWORD=Admin123!
ADMIN_FIRST_NAME=Admin
ADMIN_LAST_NAME=TaskHub

# Database
# DATABASE_PATH=./data/taskhub.db

# Bitrix24 OAuth (fill in your credentials)
BITRIX_CLIENT_ID=
BITRIX_CLIENT_SECRET=

# AI (optional, leave empty to disable AI features)
OPENROUTER_API_KEY=

# Encryption
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# App URL
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Cron (enable in dev if needed)
# ENABLE_CRON=true

# ===== LiveKit (Meetings) =====
LIVEKIT_URL=ws://localhost:7880
NEXT_PUBLIC_LIVEKIT_URL=ws://localhost:7880
LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
MEETING_WORKER_URL=http://localhost:3100
EOF

    ok ".env.local created with generated secrets"
else
    ok ".env.local already exists"

    # Check for missing ENCRYPTION_KEY
    if ! grep -q "^ENCRYPTION_KEY=.\+" "$ENV_FILE" 2>/dev/null; then
        ENCRYPTION_KEY=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
        echo "" >> "$ENV_FILE"
        echo "# Added by deploy-dev.sh" >> "$ENV_FILE"
        echo "ENCRYPTION_KEY=${ENCRYPTION_KEY}" >> "$ENV_FILE"
        warn "ENCRYPTION_KEY was missing — generated and appended to .env.local"
    fi
fi

# --------------------------------------------------
# 5. Generate VAPID keys if missing
# --------------------------------------------------
if ! grep -q "^VAPID_PUBLIC_KEY=.\+" "$ENV_FILE" 2>/dev/null; then
    info "Generating VAPID keys for push notifications..."

    VAPID_OUTPUT=$(node scripts/generate-vapid-keys.js 2>/dev/null)
    VAPID_PUB=$(echo "$VAPID_OUTPUT" | grep "^VAPID_PUBLIC_KEY=" | cut -d= -f2)
    VAPID_PRIV=$(echo "$VAPID_OUTPUT" | grep "^VAPID_PRIVATE_KEY=" | cut -d= -f2)

    if [ -n "$VAPID_PUB" ] && [ -n "$VAPID_PRIV" ]; then
        cat >> "$ENV_FILE" <<EOF

# Web Push (VAPID) — generated by deploy-dev.sh
VAPID_PUBLIC_KEY=${VAPID_PUB}
VAPID_PRIVATE_KEY=${VAPID_PRIV}
VAPID_SUBJECT=mailto:admin@taskhub.local
NEXT_PUBLIC_VAPID_PUBLIC_KEY=${VAPID_PUB}
EOF
        ok "VAPID keys generated and added to .env.local"
    else
        warn "Could not generate VAPID keys. Run manually: npm run vapid:generate"
    fi
else
    ok "VAPID keys already configured"
fi

# --------------------------------------------------
# 5b. Ensure LiveKit keys present (Meetings module)
# --------------------------------------------------
if ! grep -q "^LIVEKIT_API_KEY=.\+" "$ENV_FILE" 2>/dev/null; then
    info "Generating LiveKit keys for Meetings module..."
    LK_KEY="APIdev$(node -e "console.log(require('crypto').randomBytes(6).toString('hex'))")"
    LK_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
    cat >> "$ENV_FILE" <<EOF

# ===== LiveKit (Meetings) — generated by deploy-dev.sh =====
LIVEKIT_URL=ws://localhost:7880
NEXT_PUBLIC_LIVEKIT_URL=ws://localhost:7880
LIVEKIT_API_KEY=${LK_KEY}
LIVEKIT_API_SECRET=${LK_SECRET}
MEETING_WORKER_URL=http://localhost:3100
EOF
    ok "LiveKit keys generated and added to .env.local"
    warn "Sync keys into infra/livekit.yaml 'keys:' section before running docker compose"
else
    ok "LiveKit keys already configured"
fi

# --------------------------------------------------
# 6. Type-check (root + meeting-server)
# --------------------------------------------------
info "Running root type-check..."
if npm run type-check 2>&1; then
    ok "Root type-check passed"
else
    error "Root type-check failed. Fix errors before continuing."
    exit 1
fi

if [ -d "$PROJECT_DIR/meeting-server" ]; then
    info "Running meeting-server type-check..."
    pushd "$PROJECT_DIR/meeting-server" > /dev/null
    if npx tsc --noEmit 2>&1; then
        ok "meeting-server type-check passed"
    else
        popd > /dev/null
        error "meeting-server type-check failed."
        exit 1
    fi
    popd > /dev/null
fi

# --------------------------------------------------
# 7. Encrypt existing tokens (idempotent)
# --------------------------------------------------
info "Running token encryption migration (idempotent)..."
if npx tsx scripts/encrypt-existing-tokens.ts 2>&1; then
    ok "Token encryption migration complete"
else
    warn "Token encryption skipped (database may not exist yet — will run on first sync)"
fi

# --------------------------------------------------
# 8. Summary
# --------------------------------------------------
echo ""
echo "============================================"
echo -e "  ${GREEN}Dev environment ready!${NC}"
echo "============================================"
echo ""
echo "  Start dev server:    npm run dev"
echo "  DB studio:           npm run db:studio"
echo "  App URL:             http://localhost:3000"
echo "  Admin login:         admin@taskhub.local"
echo ""
echo "  Meetings module (LiveKit) — bundled into root docker-compose:"
echo "    Sync LIVEKIT_API_KEY/SECRET from .env.local into infra/livekit.yaml"
echo "    Full stack (prod):   docker compose --env-file .env.production up --build"
echo "    Meeting-worker dev:  cd meeting-server && npm run dev"
echo "    Worker health:       curl http://localhost:3100/health"
echo ""
echo "  Optional:"
echo "    Fill in BITRIX_CLIENT_ID/SECRET in .env.local"
echo "    Fill in OPENROUTER_API_KEY for AI features"
echo ""
