/**
 * Workspace asset service: persist & serve image files.
 *
 * Two flavours:
 *   - `kind: 'upload'` — user dragged a file into the chat / canvas.
 *   - `kind: 'ai'` — generated by `lib/workspaces/ai.ts:generateImage`.
 *
 * Storage layout (mirrors `data/meeting-uploads/`):
 *
 *   data/workspace-assets/<workspaceId>/<uuid>_<safeName>.<ext>
 *
 * The DB row records the absolute path, MIME, dimensions and the user
 * who produced the asset (NULL for AI). Reads go through `readAssetFile`
 * which guards against directory traversal even though the path was
 * generated by us — defense in depth, the cost is negligible.
 *
 * The HTTP layer (route.ts files) handles auth + content-type. Service
 * functions are pure I/O — they assume the caller has authorised the
 * user.
 */

import { db } from '@/lib/db';
import { workspaceAssets } from '@/lib/db/schema';
import { eq } from 'drizzle-orm';
import { randomUUID } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import type { WorkspaceAsset, WorkspaceAssetKind } from '@/types/workspace';

// ==================== Configuration ====================

/**
 * Allow a small, well-understood whitelist of image MIME types. We
 * exclude SVG by default because it can carry inline JS — re-enable
 * here only if a sanitiser is added in front of the serving route.
 */
const ALLOWED_MIMES: Readonly<Set<string>> = new Set([
  'image/png',
  'image/jpeg',
  'image/jpg', // some browsers send this
  'image/webp',
  'image/gif',
]);

/** 25 MiB cap, same as meeting uploads. */
const MAX_BYTES = 25 * 1024 * 1024;

/** Where files land. Override with WORKSPACE_ASSETS_DIR env var. */
function getRoot(): string {
  return (
    process.env.WORKSPACE_ASSETS_DIR ??
    path.join(process.cwd(), 'data', 'workspace-assets')
  );
}

// ==================== Public API ====================

export interface SaveAssetInput {
  workspaceId: number;
  /** Image bytes — must already be < MAX_BYTES. */
  buffer: Buffer;
  /** Lowercased MIME, e.g. `image/png`. */
  mime: string;
  /** Optional user id — null for AI-generated assets. */
  uploadedBy: number | null;
  kind: WorkspaceAssetKind;
  /** Original filename (for the disk filename suffix). Sanitised on write. */
  fileName?: string;
  /** Pre-probed dimensions. If null, we probe with sharp ourselves. */
  width?: number | null;
  height?: number | null;
}

/**
 * Persist a binary asset to disk + DB. Returns the canonical asset row
 * including its newly assigned id.
 *
 * Throws on:
 *   - empty / oversize buffer
 *   - disallowed MIME
 *   - corrupt image (sharp probe fails)
 *   - filesystem write failure (no orphan rows are created — the DB
 *     insert is conditional on the write succeeding)
 */
export async function saveAsset(input: SaveAssetInput): Promise<WorkspaceAsset> {
  if (!Number.isInteger(input.workspaceId) || input.workspaceId <= 0) {
    throw new Error('saveAsset: workspaceId must be a positive integer');
  }
  if (!Buffer.isBuffer(input.buffer)) {
    throw new Error('saveAsset: buffer must be a Buffer');
  }
  if (input.buffer.byteLength === 0) {
    throw new Error('saveAsset: buffer is empty');
  }
  if (input.buffer.byteLength > MAX_BYTES) {
    throw new Error(`saveAsset: buffer exceeds ${MAX_BYTES} bytes`);
  }
  const mime = (input.mime || '').toLowerCase();
  if (!ALLOWED_MIMES.has(mime)) {
    throw new Error(`saveAsset: MIME ${mime} not allowed`);
  }

  // Probe dimensions if not provided. We treat unknowable dimensions as
  // a corrupt-image signal and reject so the canvas never tries to
  // render a 0×0 rect.
  let width: number | null = input.width ?? null;
  let height: number | null = input.height ?? null;
  if (width == null || height == null) {
    const dims = await readImageDimensions(input.buffer);
    if (!dims) {
      throw new Error('saveAsset: failed to probe image dimensions');
    }
    width = dims.width;
    height = dims.height;
  }

  const safeName = sanitizeFileName(input.fileName ?? `image.${extFromMime(mime)}`);
  const root = getRoot();
  const wsDir = path.join(root, String(input.workspaceId));
  fs.mkdirSync(wsDir, { recursive: true });

  const storedName = `${randomUUID()}_${safeName}`;
  const absolutePath = path.join(wsDir, storedName);

  // Containment check against traversal — should never trigger because
  // both segments are sanitised, but the cost is one path.resolve.
  const resolvedRoot = path.resolve(root);
  const resolvedAbs = path.resolve(absolutePath);
  if (!resolvedAbs.startsWith(resolvedRoot + path.sep)) {
    throw new Error('saveAsset: refusing to write outside the assets root');
  }

  await fs.promises.writeFile(absolutePath, input.buffer);

  // Insert AFTER the file is on disk — orphaned bytes are easier to
  // sweep later than orphaned DB rows.
  let row: WorkspaceAsset;
  try {
    row = db
      .insert(workspaceAssets)
      .values({
        workspaceId: input.workspaceId,
        kind: input.kind,
        filePath: absolutePath,
        mime,
        width,
        height,
        uploadedBy: input.uploadedBy,
      })
      .returning()
      .get();
  } catch (err) {
    // Best-effort cleanup so we don't leak disk on insert failure.
    try {
      await fs.promises.unlink(absolutePath);
    } catch {
      // ignore — file may be already gone
    }
    throw err;
  }

  return row;
}

/** Fetch a single asset row by id. Returns null when missing. */
export function getAsset(assetId: number): WorkspaceAsset | null {
  if (!Number.isInteger(assetId) || assetId <= 0) return null;
  const row = db
    .select()
    .from(workspaceAssets)
    .where(eq(workspaceAssets.id, assetId))
    .get();
  return row ?? null;
}

/** Fetch all assets attached to a workspace, newest first. */
export function listAssets(workspaceId: number): WorkspaceAsset[] {
  if (!Number.isInteger(workspaceId) || workspaceId <= 0) return [];
  return db
    .select()
    .from(workspaceAssets)
    .where(eq(workspaceAssets.workspaceId, workspaceId))
    .all()
    .sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1));
}

export interface ReadAssetResult {
  buffer: Buffer;
  mime: string;
  width: number | null;
  height: number | null;
  /** Sanitised basename (no path) — useful for Content-Disposition. */
  fileName: string;
  /** Asset row used for cache headers (workspaceId, createdAt). */
  asset: WorkspaceAsset;
}

/**
 * Read the bytes of an asset off disk. Returns null when the asset row
 * is missing or the file is no longer on disk (e.g. someone wiped the
 * data dir).
 */
export async function readAssetFile(assetId: number): Promise<ReadAssetResult | null> {
  const asset = getAsset(assetId);
  if (!asset) return null;

  const root = getRoot();
  const resolvedRoot = path.resolve(root);
  const resolvedAbs = path.resolve(asset.filePath);
  // Defensive containment in case the DB row was tampered with.
  if (!resolvedAbs.startsWith(resolvedRoot + path.sep)) {
    return null;
  }

  let buffer: Buffer;
  try {
    buffer = await fs.promises.readFile(asset.filePath);
  } catch (err) {
    // Missing file → null so the route can return 404 cleanly.
    if ((err as NodeJS.ErrnoException)?.code === 'ENOENT') return null;
    throw err;
  }

  return {
    buffer,
    mime: asset.mime,
    width: asset.width,
    height: asset.height,
    fileName: path.basename(asset.filePath),
    asset,
  };
}

/** True iff `assetId` is owned by `workspaceId`. */
export function assetBelongsToWorkspace(
  assetId: number,
  workspaceId: number
): boolean {
  const asset = getAsset(assetId);
  return Boolean(asset && asset.workspaceId === workspaceId);
}

// ==================== Helpers ====================

/**
 * Probe width/height with sharp. Dynamic import keeps the cold path
 * lean (we only pay sharp's startup cost when an image is actually
 * uploaded).
 */
async function readImageDimensions(
  buffer: Buffer
): Promise<{ width: number; height: number } | null> {
  try {
    const sharpModule = await import('sharp');
    const sharpFactory = (sharpModule.default ?? sharpModule) as unknown as (
      input: Buffer
    ) => { metadata: () => Promise<{ width?: number; height?: number }> };
    const meta = await sharpFactory(buffer).metadata();
    const width = typeof meta.width === 'number' ? meta.width : null;
    const height = typeof meta.height === 'number' ? meta.height : null;
    if (!width || !height || width <= 0 || height <= 0) return null;
    return { width, height };
  } catch (err) {
    console.warn('[workspaces/assets] sharp metadata failed:', err);
    return null;
  }
}

function sanitizeFileName(raw: string): string {
  const stripped = path.basename(raw);
  const cleaned = stripped
    .replace(/[\x00-\x1f\x7f]/g, '')
    .replace(/[\\/:*?"<>|]/g, '_')
    .replace(/\s+/g, ' ')
    .trim();
  if (!cleaned) return 'image';
  const safe = cleaned.startsWith('.') ? cleaned.slice(1) : cleaned;
  return safe.slice(0, 120) || 'image';
}

function extFromMime(mime: string): string {
  switch (mime) {
    case 'image/png':
      return 'png';
    case 'image/jpeg':
    case 'image/jpg':
      return 'jpg';
    case 'image/webp':
      return 'webp';
    case 'image/gif':
      return 'gif';
    default:
      return 'bin';
  }
}

/** Re-export so the route can give consistent error messages. */
export const ALLOWED_ASSET_MIMES = ALLOWED_MIMES;
export const MAX_ASSET_BYTES = MAX_BYTES;
